before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
brew:
  github:
    owner: vromero
    name: homebrew-tap
  folder: Formula
  homepage:  https://goreleaser.com
  description: Deliver Go binaries as fast and easily as possible
  test: |
    system "#{bin}/goreleaser -v"
scoop:
  bucket:
    owner: vromero
    name: scoop-bucket
  homepage:  https://goreleaser.com
  description: Deliver Go binaries as fast and easily as possible
  license: MIT
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  vendor: "Victor Romero"
  homepage: "https://gofortune.github.io"
  maintainer: "Victor romero <victor.romero@gmail.com>"
  description: "Implementation of the fortune unix tools: fortune and strfile."
  license: "Apache 2.0"
  formats:
    - deb
    - rpm

